project.name=PrepareWeb3
project.version=1.0-SNAPSHOT
main.class=app.Lab3Launcher

src.dir=java
test.src.dir=test
resources.dir=resources
webapp.dir=webapp

build.dir=build
classes.dir=${build.dir}/classes
test.classes.dir=${build.dir}/test-classes
test.reports.dir=${build.dir}/test-reports

dist.dir=dist
dist.jar=${dist.dir}/${project.name}.jar
manifest.file=MANIFEST.MF

lib.dir=lib
ivy.jar=${lib.dir}/ivy-2.5.2.jar
ivy.url=https://repo1.maven.org/maven2/org/apache/ivy/ivy/2.5.2/ivy-2.5.2.jar

music.command=afplay
music.file=/System/Library/Sounds/Glass.aiff

git.command=git
ant.command=ant
history.output.dir=history-output
history.diff.file=history-output/last-working-revision.diff
history.worktree.dir=../history-worktree